Project done
webmarkyn/restaurant-page pull request #1
Opened 2020-01-08 19:21 UTC by webmarkyn

Finished Restaurant page project.
Used npm, webpack, import/export features.
Every DOM element is separated into its own module that's a function with returns a DOM element with styles and HTML and then get's added to page's DOM dynamically.
For linting used ESLINT

2020-01-08 19:41 UTC, webmarkyn commented
Please run "npm start" to build the project. Then you can open index.html file

2020-01-09 00:18 UTC, bellom requested changes
## Hi @webmarkyn  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1:, just few issues left to work on............ :slightly_smiling_face: 

Below are part of the checklist for this project, kindly work on these few things listed below;
1. 
It features a tabbed menu. When a tab is clicked the content is replaced ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/tab_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page))
![image](https://user-images.githubusercontent.com/31897434/72026230-143b0580-327b-11ea-8b47-d09111b5b99c.png)
As you can see the above instructions, once you clicked on one tab, it will wipe out the content not just part of the content.
**Screenshot from your web app below;**
![image](https://user-images.githubusercontent.com/31897434/72026669-8f50eb80-327c-11ea-89bd-e0ba4eee06c1.png)

**Hint:** Below screenshot is what we call tab menu in this project context.
![image](https://user-images.githubusercontent.com/31897434/72026757-e951b100-327c-11ea-95d1-4e45e34833c7.png)

Example of tabbed browsing is also shown here 👇 
![image](https://user-images.githubusercontent.com/31897434/72027011-c8d62680-327d-11ea-99e8-5ae1bf8877fa.png)
https://www.hongkiat.com/blog/50-nice-clean-css-tab-based-navigation-scripts/


2. Kindly work on my comments below


**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-01-09 00:18 UTC, bellom commented on src/article.component.js
> +  articleEl.style.cssText = `
Let try as much as possible to keep our styling in CSS files, i believe we are all trying hard to practice good way of writing code. 👍 
![image](https://user-images.githubusercontent.com/31897434/72025603-ee146600-3278-11ea-9213-b8e2c924c445.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/

2020-01-09 00:18 UTC, bellom commented on src/article.component.js
> +  p.style.cssText = `
Let try as much as possible to keep our styling in CSS files, i believe we are all trying hard to practice good way of writing code. 👍 
![image](https://user-images.githubusercontent.com/31897434/72025603-ee146600-3278-11ea-9213-b8e2c924c445.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/

2020-01-09 00:18 UTC, bellom commented on src/header.component.js
> +        width: 100%;
Let try as much as possible to keep our styling in CSS files, i believe we are all trying hard to practice good way of writing code. 👍 
![image](https://user-images.githubusercontent.com/31897434/72025603-ee146600-3278-11ea-9213-b8e2c924c445.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/

2020-01-09 00:18 UTC, bellom commented on src/tabs.component.js
> +  tabsEl.style.cssText = `
Let try as much as possible to keep our styling in CSS files, i believe we are all trying hard to practice good way of writing code. 👍 
![image](https://user-images.githubusercontent.com/31897434/72025603-ee146600-3278-11ea-9213-b8e2c924c445.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/

2020-01-09 19:40 UTC, bellom approved these changes
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

**I trust you can improve the app, by using the tabbed browsing style used as an example in Odin page.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Goodluck in the next project :slightly_smiling_face:_ 

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-01-21 09:58 UTC, merged